apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-examples
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Terraform Web Server with vars example
    source:
      repo: https://github.com/yogitaupadhyay/terraform-google-cloud-examples.git
      sourceType: git
      dir: /code/04-one-webserver-with-vars
    version: 0.17.2
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  content: {}
  interfaces:
    variables:
      - name: server_port
        description: The port the server will use for HTTP requests
        defaultValue: "8080"
    outputs:
      - name: public_ip
