apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-cloud-examples
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Add your title here
    source:
      repo: https://github.com/yogitaupadhyay/terraform-google-cloud-examples.git
      sourceType: git
      dir: /code/01-hello-world
    version: 0.17.2
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  content: {}
  interfaces: {}
  requirements:
    roles:
      - level: Project
        roles:
          - roles/accesscontextmanager.policyAdmin
          - roles/orgpolicy.policyAdmin
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.co
    providerVersions:
      - source: hashicorp/google
        version: ">= 6, < 7"
      - source: hashicorp/google-beta
        version: ">= 6, < 7"
